---
- name: Create directory
  file:
    path: $HOME/info
    state: directory
  register: dir_path

- name: Copy docker-compose file
  copy:
    src: ../files/docker-compose-adh.yaml
    dest: $HOME/info/docker-compose.yaml

- name: Set-up docker-compose
  community.docker.docker_compose: #pip3 install docker && pip3 install docker-compose
    project_src: "{{ dir_path.path }}"
  register: result
  become: True

- debug:
    msg: "{{ result.actions }}"
  when: result.failed == True
